server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: top-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangHuiLearn/topShopping.git
          username: ZhangHuiLearn
          password: zhang404hui