spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001
spring:
  profiles: dev #开发环境
  application:
    name: user-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///topshopping
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
mybatis-plus:
  type-aliases-package: cn.top.domain,cn.top.query
feign:
  hystrix:
    enabled: true
---
server: 
  port: 8001
spring:
  profiles: test #测试环境
  application:
    name: user-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///topshopping
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
mybatis-plus:
  type-aliases-package: cn.top.domain,cn.top.query
feign:
  hystrix:
    enabled: true
---
server: 
  port: 8001
spring:
  profiles: prod #生产环境
  application:
    name: user-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///topshopping
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
mybatis-plus:
  type-aliases-package: cn.top.domain,cn.top.query
feign:
  hystrix:
    enabled: true